name: ape-roll

plugins:
  - name: solidity
  - name: etherscan
  - name: foundry
  - name: infura

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.1.0

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.1.0"

ethereum:
  local:
    default_provider: foundry
  mainnet_fork:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura

      #foundry:
      #  fork:
      #    ethereum:
      #      mainnet:
      #        upstream_provider: geth
      #
      # ethereum:
      #   default_network: mainnet-fork
      #   mainnet_fork:
      #     default_provider: foundry
