name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache compiler installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: ${{ runner.os }}-compiler-cache

      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13

      - name: Install dependencies
        run: poetry install

      - name: Install ape plugins
        run: poetry run ape plugins install -y .

      - name: Install ape-foundry
        run: poetry run ape plugins install foundry infura

      - name: Compile Code
        run: poetry run ape compile --size

      - name: Run Tests
        env:
          ETHERSCAN_TOKEN: MW5CQA6QK5YMJXP2WP3RA36HM5A7RA1IHA
          WEB3_INFURA_PROJECT_ID: b7821200399e4be2b4e5dbdf06fbe85b
        run: poetry run ape test --networks
